image: maven:3-jdk-11

variables:
  GIT_STRATEGY: "clone"

stages:
  - test
  - build
  - deploy

test-backend:
  stage: test
  image: maven:3-jdk-11
  script:
    - cd backend
    - mvn -B clean install

test-frontend:
  stage: test
  image: node:lts
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour
